UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'glozira.a.mapalo@pwc.com' AND Username = 'Mapalo, Glozira A.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ram.steven.naval@pwc.com' AND Username = 'Naval, Ram Steven Martin S.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'charlize.gabriele.linantud@pwc.com' AND Username = 'Linantud, Charlize Gabriele L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'daniel.u.buenaobra@pwc.com' AND Username = 'BUENAOBRA, DANIEL U.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'faith.a.dalawangbayan@pwc.com' AND Username = 'Dalawangbayan, Faith A.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'joira.berlina.azurin@pwc.com' AND Username = 'Azurin, Joira Berlina A.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'vicrosendo.c.cuyos@pwc.com' AND Username = 'Cuyos, Vicrosendo C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'paul.vincent.dela.cruz@pwc.com' AND Username = 'Dela Cruz, Paul Vincent L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'samantha.corrinne.rantael@pwc.com' AND Username = 'Rantael, Samantha Corrinne G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'rysa.belle.laudit@pwc.com' AND Username = 'Laudit, Rysa Belle B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'francesca.beatriz.jayme@pwc.com' AND Username = 'Jayme, Francesca Beatriz R.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'richelyn.l.caburog@pwc.com' AND Username = 'CABUROG, RICHELYN L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jacob.l.santillan@pwc.com' AND Username = 'Santillan, Jacob L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'aubrey.gayle.diaz@pwc.com' AND Username = 'Diaz, Aubrey Gayle T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'emmelyn.mae.jimenez@pwc.com' AND Username = 'Jimenez, Emmelyn Mae O.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'king.matthew.tria-tirona@pwc.com' AND Username = 'Tria-Tirona, King Matthew G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'camille.katherine.gerawa@pwc.com' AND Username = 'Gerawa, Camille Katherine P.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'john.lorenz.vasquez@pwc.com' AND Username = 'Vasquez, John Lorenz D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kim.julianne.dolor@pwc.com' AND Username = 'Dolor, Kim Julianne T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'patricia.iole.herrera@pwc.com' AND Username = 'Herrera, Patricia Iole C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ashley.t.villaflores@pwc.com' AND Username = 'Villaflores, Ashley T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'matthew.l.lim@pwc.com' AND Username = 'Lim, Matthew Marcus P.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'maria.dominique.rellosa@pwc.com' AND Username = 'Rellosa, Maria Dominique C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jerry.anne.brioso@pwc.com' AND Username = 'Brioso, Jerry Anne, M.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'angel.prima.bugarin@pwc.com' AND Username = 'Bugarin, Angel Prima A.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'zenia.beatriz.calixterio@pwc.com' AND Username = 'Calixterio, Zenia Beatriz DC';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'francheska.d.david@pwc.com' AND Username = 'David, Francheska D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'nathan.john.deypalan@pwc.com' AND Username = 'Deypalan, Nathan John N.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'rhiza.sophia.teddy@pwc.com' AND Username = 'Teddy, Rhiza Sophia';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'patricia.gail.ello@pwc.com' AND Username = 'Ello, Patricia Gail C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'julio.r.reyes@pwc.com' AND Username = 'Reyes, Julio II T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'michaela.denise.santos@pwc.com' AND Username = 'Santos, Michaela Denise G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'daryll.d.tampal@pwc.com' AND Username = 'Tampal, Daryll D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'julius.rhey.pendos@pwc.com' AND Username = 'Pendos, Julius Rhey M.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'rona.l.villaflor@pwc.com' AND Username = 'Villaflor, Rona L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'juliana.rae.dichoso@pwc.com' AND Username = 'Dichoso, Juliana Rae M.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'rhamuel.johnber.ramos@pwc.com' AND Username = 'Ramos, Rhamuel Johnber R.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'joemari.t.cruz@pwc.com' AND Username = 'Cruz, Joemari T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'roel.e.orbillo@pwc.com' AND Username = 'Orbillo Roel Jr Enosa';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'joanna.t.tan@pwc.com' AND Username = 'Tan, Joanna A.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'josef.balares@pwc.com' AND Username = 'Balares, Josef R.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'bella.corazon.reyes@pwc.com' AND Username = 'Reyes, Bella Corazon B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ma.beatriz.sanchez@pwc.com' AND Username = 'Sanchez, Ma. Beatriz B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'stanley.matthew.aquino@pwc.com' AND Username = 'Aquino, Stanley Matthew D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'hannah.keithlene.cacas@pwc.com' AND Username = 'Cacas, Hannah Keithlene L';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jarell.james.ignacio@pwc.com' AND Username = 'Ignacio, Jarell James G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'john.g.ponce@pwc.com' AND Username = 'Ponce, John Kenneth G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jae.marie.marifosque@pwc.com' AND Username = 'Marifosque, Jae Marie A.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'james.d.deri@pwc.com' AND Username = 'Deri James D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'draconsel.c.yasol@pwc.com' AND Username = 'Yasol, Draconsel C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'anne.jelyne.lorina@pwc.com' AND Username = 'Loriña, Anne Jelyne V';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'nicole.de.los.santos@pwc.com' AND Username = 'De los Santos, Nicole M.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'margaret.ann.gatpolintan@pwc.com' AND Username = 'Gatpolintan, Margaret Ann V.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jezza.t.tabunan@pwc.com' AND Username = 'Tabunan, Jezza T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'denise.c.perez@pwc.com' AND Username = 'Perez, Denise C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'irish.c.valera@pwc.com' AND Username = 'Valera, Irish Giorgia C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'joecel.b.gumalas@pwc.com' AND Username = 'Gumalas, Joecel B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ron.p.doronila@pwc.com' AND Username = 'Doronila, Ron Justin P.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jethro.timothy.cornejo@pwc.com' AND Username = 'Cornejo, Jethro Timothy E.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'gian.romeo.b.caridad@pwc.com' AND Username = 'Caridad, Gian Romeo B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'maricel.buan@pwc.com' AND Username = 'Labrador, Maricel B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'wendilyn.yecyec@pwc.com' AND Username = 'Yecyec, Wendilyn D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'richelle.marie.natonton@pwc.com' AND Username = 'Natonton, Richelle Marie C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'khalil.p.medina@pwc.com' AND Username = 'Medina, Khalil P.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'raffy.dela.cruz@pwc.com' AND Username = 'Dela Cruz Raffy C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ivan.arjay.yano@pwc.com' AND Username = 'Yano, Ivan Arjay C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'paul.adrian.capili@pwc.com' AND Username = 'Capili, Paul Adrian S.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kristine.anne.cablao@pwc.com' AND Username = 'Cablao, Kristine Anne D.P.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kimberly.c.du@pwc.com' AND Username = 'Dupagan, Kimberly D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jodin.lars.caipang@pwc.com' AND Username = 'Caipang, Jodin Lars R.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jiselle.l.resurreccion@pwc.com' AND Username = 'Resurreccion, Jiselle L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kenneth.r.torrente@pwc.com' AND Username = 'Torrente. Kenneth R.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'charmaine.l.mampusti@pwc.com' AND Username = 'Mampusti, Charmaine L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'rico.mahilum@pwc.com' AND Username = 'Mahilum Rico D';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'lianna.b.capuno@pwc.com' AND Username = 'Capuno, Lianna';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'noreen.faye.costuna@pwc.com' AND Username = 'Teodoro, Noreen Faye';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'justine.mae.cortuna@pwc.com' AND Username = 'Cortuna, Justine Mae T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jia.t.ocayo@pwc.com' AND Username = 'Ocayo, Jia T.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'marie.iryanna.yu@pwc.com' AND Username = 'Yu, Marie Iryanna D';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'mae.jonina.camu@pwc.com' AND Username = 'Camu, Mae Jonina Shaira V.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kahle.kc.valencia@pwc.com' AND Username = 'Valencia, Kahle KC Raves C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'franco.e.veras@pwc.com' AND Username = 'Veras, Franco Jr. E.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ancherina.marie.retes@pwc.com' AND Username = 'Retes, Ancherina Marie G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'alondra.b.pastorin@pwc.com' AND Username = 'Pastorin, Alondra B.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kim.alexis.papa@pwc.com' AND Username = 'Papa, Kim Alexis C.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'carl.luiz.fabula@pwc.com' AND Username = 'Fabula, Carl Luiz L.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kayla.d.espino@pwc.com' AND Username = 'Espino, Kayla D.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'patricia.monica.panalangin@pwc.com' AND Username = 'Panalangin, Patricia Monica S.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'angelica.v.roxas@pwc.com' AND Username = 'Roxas, Angelica V.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jhazzie.g.dolor@pwc.com' AND Username = 'Dolor, Jhazzie Lindsay G.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'princess.ea.escarda@pwc.com' AND Username = 'Escarda, Princess Ea P.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jillian.mitziko.limqueco@pwc.com' AND Username = 'Jillian Mitziko C. Limqueco';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'kyle.christopher.quiogue@pwc.com' AND Username = 'Kyle Christopher G Quiogue';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'facel.r.mercado@pwc.com' AND Username = 'Mercado, Facel Kate R.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jasmin.v.salvador@pwc.com' AND Username = 'Salvador, Jasmin V.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'mary.rose.lara@pwc.com' AND Username = 'Lara, Mary Rose H.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'hans.c.cruz@pwc.com' AND Username = 'Dela Cruz, Hans Even M.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'jeffrey.s.requiso@pwc.com' AND Username = 'Requiso, Jeffrey S.';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'ma.veronica.s.sales@pwc.com' AND Username = 'Sales, Ma veronica S';
UPDATE tbl_Users SET IsWinner = 1 WHERE Email = 'castaneda.michael@pwc.com' AND Username = 'Michael Castañeda';